### ISSUE TITLE
[Collaboration] Combining your module with MMM-Remote-Control

### ISSUE THREAD

**Issue by shbatm** [juzim/MMM-Api#1]
Hello,

I think you have an awesome idea here for "discovering" API functions of other modules. I hope you don't mind, but I took the concept you developed and incorporated it into a large update to MMM-Remote-Control that I'm hoping to merge (jopyth/MMM-Remote-Control#104).  I wasn't sure if you were on the MM forum, so I thought I'd raise an issue here instead.  

I took your idea and expanded it to allow other modules to also send a notification to detail their API explicitly.

If you're interested, please check out the implementation here:
https://github.com/shbatm/MMM-Remote-Control/tree/upstream_pr/API

Thanks for the awesome work!

**Comment by juli-dot-md** [comment]
Thanks for the credit!

The API was supposed to be a first step for an integration into [home assistant](https://www.home-assistant.io/). The idea was to have a component (or even a new 'display' category) to control multiple magic mirrors for scenarios like "Start a video of the local news on the bathroom mirror when I enter the room for the first time before 9 am" which would be overkill for MMM itself.

I never found the time to finish it, great to hear that it still might be of help!

**Comment by shbatm** [comment]
Heading down the same path... I was looking to clean up and standardize the calls I have coming from my Hass setup and ISY
